CompanyName: CSSNR
FileDescription: Brew Python Resources
InternalName: Brew Python Resources
LegalCopyright: https://cssnr.com/
OriginalFilename: bpr.exe
ProductName: Brew Python Resources
Version: 0.0.0.1
